### ISSUE TITLE
Jaw Motor Movement problem.

### ISSUE THREAD

**Issue by super-ste** [robotology/icub-support#16]
Katrin from Heriott-Watt requests:
we are getting a error from the jaw motor now and it is not moving after it first moved very very slowly.

**Comment by super-ste** [comment]
Replied that iCub-Support Team is travelling until April 28th and requests logs in hte meanwhile.

**Comment by BrutusTT** [comment]
Log file from robotInterface can be found here: http://pastebin.com/EJiXED86

**Comment by super-ste** [comment]
Update per Ingo:
I attached the log file that shows the failing motor for face joint 0.

In the recent days I also have seen head joint 0 sometimes failing but it was not consistent enough for me to take a log. In contrast to the face joint 0 for the head joint 0 I was able to use the robotMotorGui to switch it idle and run again. Which worked for the head motor but not for the face one.

cc @maggia80 @randaz81 can you also have a look so we can gather ideas for Wednesay when we will be able to intervene?

**Comment by super-ste** [comment]
@BrutusTT 
please note this line in the log you sent.

``` [ERROR]TalkingFace_Calibrator : unable to clear the hardware fault detected on joint  0  before starting the calibration procedure! ```

This tells you that robotInterface cannot clear an error prevoiusly encountered. 
Please provide a log after a clean start so we can assess the root couse of the problem.

cc @julijenv

**Comment by BrutusTT** [comment]
Thats the problem we are trying to solve. It was a clean start. Everything was switched off and on again before starting the robotInterface.

We even tested it with enforcing the cleaning by putting the clearHwFaultBeforeCalibration flag into the proper config file. But it wasn't able to clear the HWFAULT state.

**Comment by randaz81** [comment]
According to the line:
`[DEBUG]TalkingFace_Calibrator : set 1 j 0 : Calibrating... enc values AFTER calib:  -87.0769`
I suspect an hardware issue in the AEA encoder of the jaw. In this case, the joint will go in HWFAULT state immediately after the recovery attempt done by the calibrator.
To confirm this theory: can you open the robotMotorGui (after robotInterface calibration is complete) trying to manually move the jaw (gently), and checking the value of the encoder of joint 0 (face tab): correct values are in the range 0 +30deg (approx)

**Comment by KatSol** [comment]
Hi, 
I think it is not moving at all, but maybe we can just Skype?

**Comment by julijenv** [comment]
Hi @KatSol , we are closing some issues still open ion github, can you confirm that one was solved?
Lert me know

**Comment by KatSol** [comment]
Dear Julien,
no it is not solved as my student mentioned in his last email:


Hi,

after Katrin fixed the encoder problem we are still having problems with the jaw joint.

I attached two log files of different runs. The first indicates trouble with some motors during the shutdown procedure whereas the second seems to be normal.

However, in both runs the jaw motor was just making some ticking noises if I tried to set a position. As further I set the position from the initial one as much more ticking I got. We were wondering if this might be due to a problem with the internal gears or something like this.

Thanks,
Ingo

--
---
Dipl.-Inf. Ingo Keller
PhD Student

School of Mathematical and Computer Sciences
EM Building, Room 2.22 (RoboticsLab)
Heriot-Watt University
Edinburgh, Scotland
EH14 4AS, United Kingdom
http://www.macs.hw.ac.uk/RoboticsLab/


Best regards,
Katrin

Dr. Katrin S. Lohan

Deputy Director of the Robotics Laboratory
Assistant Professor/Lecturer in Computer Science and Robotics

School of Mathematical and Computer Sciences
Heriot-Watt University
Edinburgh
K.Lohan@hw.ac.uk<mailto:K.Lohan@hw.ac.uk>

On 16 Jul 2015, at 16:51, julien <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @KatSol<https://github.com/KatSol> , we are closing some issues still open ion github, can you confirm that one was solved?
Lert me know

—
Reply to this email directly or view it on GitHub<https://github.com/robotology/icub-support/issues/16#issuecomment-121999707>.



----- 
We invite research leaders and ambitious early career researchers to 
join us in leading and driving research in key inter-disciplinary themes. 
Please see www.hw.ac.uk/researchleaders for further information and how
to apply.

Heriot-Watt University is a Scottish charity
registered under charity number SC000278.

**Comment by BrutusTT** [comment]
The logs can be found here http://pastebin.com/8cUYNUyP and here http://pastebin.com/8a1qa5Uz

**Comment by pattacini** [comment]
ping @julijenv

**Comment by julijenv** [comment]
Hi Edinburgh user of the icub talking head,
AFAI can tell, thre is no way to understand what's going wrong on your jaw motor from the log files sent, please get in contact with us with skype ID : icub-support, and let see what can be done to see whether the motor is dead or not?\
Can the motor spin when direct tension is applied to it? (0-5V max)
Let us know

**Comment by lornat75** [comment]
Any update after the skype chat?

**Comment by julijenv** [comment]
There are some problems with the AEA encoders of th jaw and the eyelids, we sent an AEA spare part to them, didnt receive any news from them.
Please @BrutusTT and @KatSol , let us know how goes the Head?

**Comment by KatSol** [comment]
The jaw motor is still not working properly.
Best regards,
Katrin
Dr. Katrin S. Lohan

Deputy Director of the Robotics Laboratory
Assistant Professor/Lecturer in Computer Science and Robotics

School of Mathematical and Computer Sciences
Heriot-Watt University
Edinburgh
K.Lohan@hw.ac.uk<mailto:K.Lohan@hw.ac.uk>

On 29 Oct 2015, at 13:01, julien <notifications@github.com<mailto:notifications@github.com>> wrote:


There are some problems with the AEA encoders of th jaw and the eyelids, we sent an AEA spare part to them, didnt receive any news from them.
Please @BrutusTT<https://github.com/BrutusTT> and @KatSol<https://github.com/KatSol> , let us know how goes the Head?

—
Reply to this email directly or view it on GitHub<https://github.com/robotology/icub-support/issues/16#issuecomment-152173329>.



----- 
We invite research leaders and ambitious early career researchers to 
join us in leading and driving research in key inter-disciplinary themes. 
Please see www.hw.ac.uk/researchleaders for further information and how
to apply.

Heriot-Watt University is a Scottish charity
registered under charity number SC000278.

**Comment by julijenv** [comment]
Hi @KatSol  and @BrutusTT ,
Please give me more details on what's going wrong. Send a logfile, try to indentify where the issue could come from.
I'm everyday behind the skypeId: icub.support just ring me, whenever u can and let's try to solve this out.
best regards,
