### ISSUE TITLE
iCub Shaking

### ISSUE THREAD

**Issue by tanismar** [robotology/icub-support#188]
Hi, 
In the last couple of days it happened a few times (2-3), that being only the modules of iCub-startup and yarpmotorgui running, the blue iCub suddenly started shaking. This happened all times after a while (~10 min) of being in that position, when I wasn't running anything else. I pressed the red button to prevent further damage, but I have no idea what could lead to this behavior. 

Best, 
Tanis

**Comment by julijenv** [comment]
Hi @tanismar , as asked to @spada1978 , just: 
EXPERIENCE 1:
1) close everything ( I mena module speaking)
2) power cycle the motors
3) yarp clean
4) dont launch any module except robotInterface
and see if the behaviour still persist to shake.
If yes, repeat phase 1 to 4 (EXPERIENCE 2) but push the red button as well.
after 10min check with yarpmotorgui or iCubgui to check if the values of the different joint are fluctuating. If you can detect the joint on which the value shake so you will have to check the wires to this sensor.
If you cant detect this specific problematic joint (sensor), you may have to repeat the EXP 1: but openyarpmotorgui and ASAP te robot start shaking try to idle joint after joint in order to find out the one  creating this bahviour.
Let me kow
