### ISSUE TITLE
Left elbow broken tendon

### ISSUE THREAD

**Issue by usigneb** [robotology/icub-support#191]
Hi all,
 I'm having some problems with our iCub.
We have broken one of the left arm elbow tendons. The video and photoes of 
the broken part are attached to my mail.

I have some extra tendons here with different lengths 
and end types (but with numbers of them). 
But I'm not sure how to replace the new tendon and which tendon to use.

Any help would be really nice.

Thanks in advance.

Bengisu

![left_elbow_front](https://cloud.githubusercontent.com/assets/15938923/13352466/2019c7ea-dc96-11e5-97d0-85a6874e74e1.jpg)
![left_elbow_front_close](https://cloud.githubusercontent.com/assets/15938923/13352470/2587d4e2-dc96-11e5-8d99-084560ad3b09.jpg)
![left_elbow_back](https://cloud.githubusercontent.com/assets/15938923/13352472/29b0aa30-dc96-11e5-8bbc-28523d845be8.jpg)

**Comment by julijenv** [comment]
re: Hi Elis,
From the pictures I guess you broke with not certainty N9 and/or 10 - hard to see if just one is broken or both.
please see this manual "shoulder wiring" on the wiki page.

http://wiki.icub.org/wiki/Tendons_and_replacement

On which you will be able to see either the size of the cable and how to wire it.
I would advise you, to remove the upper arm cover in order to proceed  with more safety the change of the cable.

In the worst case scenario please come on skype  add icub.support on your contact list and i would be here surely to assist you.

As explained on mail last reply to your previous mail please copy paste your failure on a new issue on the github/icub-support.
https://github.com/robotology/icub-support/issues

good luck let us know.

**Comment by pattacini** [comment]
@robotology/all-robotology-developers 

Lately, we've introduced a [**template**](https://github.com/robotology/icub-support/blob/master/.github/ISSUE_TEMPLATE.md) for opening up an issue here on `icub-support`.

It's composed of two sections the user is asked to fill in. Let's try to stick to this, then.

Of course @robotology/icub-support-team is free to adapt the template to their needs.

**Comment by pattacini** [comment]
The template shows up as soon as the user click on the [[**`New Issue`**]](https://github.com/robotology/icub-support/issues/new) button.

**Comment by usigneb** [comment]
Sorry. I'm new and I didn't notice. Next time I'll be careful about that.

**Comment by pattacini** [comment]
No worries @usigneb :smile:

**Comment by julijenv** [comment]
Any news with the replacement?

**Comment by julijenv** [comment]
@usigneb , any news with the replacement?
