### ISSUE TITLE
Can't start icub server

### ISSUE THREAD

**Issue by fjandrad** [robotology/icub-support#263]
The server was off so we tried to turn it on but it never connected.

We tried to ping 10.0.0.1but only answer was host is unreachable.
We tried turning everything off and on 2 times but nothing changed.

**Comment by fjandrad** [comment]
cc @mbrunettini  could you help us?

**Comment by mbrunettini** [comment]
Boot issue.
Fixed.

**Comment by pattacini** [comment]
cc @vtikha

**Comment by vtikha** [comment]
:+1:

**Comment by traversaro** [comment]
@mbrunettini how do you solved the problem? It may be helpful to know for the next times it happens.

**Comment by traversaro** [comment]
Apparently it happen again, after a mysterious automatic reboot while the server was running.

**Comment by traversaro** [comment]
cc @DanielePucci @francesco-romano

**Comment by mbrunettini** [comment]
The two issue was definitely NOT related:
1) misconfiguration on ESX bootup sequence after system upgrade.
2) ESX experienced a core dump (!!) error on June 29th, 16.31

The most recent issue was probably related to a memory issue (possible hardware fail?).
After that, the system took a lot to boot up due to filesystem checke and logs dump. Normally, the server boots up in less than 3 minutes (just checked).
Please keep the system under monitoring and let me know any anomaly.
Closing this issue and opening another one.

**Comment by traversaro** [comment]
Thanks @mbrunettini .

**Comment by claudiofantacci** [comment]
Hi guys, I've just *heard* that the server automatically reboot.
It actually happened twice.

cc @marcoaccame

**Comment by mbrunettini** [comment]
1) What doeas it means HEARD?!?!
2) This issue is closed and please do not use it, see above.
THANKS

**Comment by DanielePucci** [comment]
Refer to #265 for fishy server reboots.
