### ISSUE TITLE
Overcurrent on joint 1 of left leg

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-support#338]
When I switch on pwm on joint 1 of left leg, it goes in overcurrent fault.

**Comment by julijenv** [comment]
I'd already check last week if there was an electrical problem but couldnt find it, Could you please make some test to narrow down the reason fo this overcurrent?

**Comment by iron76** [comment]
@valegagge and @julijenv any news in this concern?

**Comment by julijenv** [comment]
Hi @valegagge,
The overcurrent was due to 2 phases of the motor touching each other. One random metallic fall inside the 2FOC board leading to link in between the 2 phases.
Everythin' has been replaced on the leg, please check if the message is gone on yarpprobotinterface.
let me know and close the issue if necessary

**Comment by traversaro** [comment]
@valegagge The robots starts and the joint goes in "Not Configured". Perhaps it was commented out in some configuration file?

**Comment by traversaro** [comment]
![jointstatus](https://cloud.githubusercontent.com/assets/1857049/21688549/92733a1e-d36d-11e6-8faa-18cee3fcf873.png)

**Comment by traversaro** [comment]
We enable the joint in calibration and everything works fine, closing the issue.
