### ISSUE TITLE
Backpack's fault jack can (not intentionally) detach itself if the backpack is vibrating and shaking  

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#341]
### Description of the failure
During a period of unwanted high frequency shaking and vibration during the balancing (caused by an external event that we still did not identify), the jack of the fault button cable detached itself from the backpack, resulting in an unwanted fault condition in the robot.

### Detailed conditions and logs of the failure

See https://github.com/robotology/codyco-superbuild/issues/160 .

It is not clear to us (@DanielePucci @gabrielenava @S-Dafarra) if this is a problem of `iCubGenova02`'s backpack or it is a design problem of the jack.

@maggia80 @julijenv

**Comment by DanielePucci** [comment]
Today, during the demo for the Voyager TV show, the robot unexpectedly fell. Postmortem analysis shows that the robot went into the fault state, even though nobody pressed the fault button. We then checked that by touching the fault jack, the robot enters into the fault state. Since during the YOGA++ demo the backpack moves, then this motion trigger the jack to move, which in turn makes the robot enter into the fault state.

@gabrielenava @traversaro @julijenv  @iron76
