### ISSUE TITLE
Left thumb not working

### ISSUE THREAD

**Issue by massimoregoli** [robotology/icub-support#365]
### Description of the failure

The tendon of the thumb abduction joint of the left hand is broken.

**Comment by julijenv** [comment]
@massimoregoli , @pattacini, 
it has been restored left thumb abduction joint, which led us to rewire all the cables of the thumb (abduction, prox and distal).
both the piece RC_TLR_012_P_034 and RC_TLR_012_P_036 has been modified due to the fact that G1-6-3--_-_U5923_ESLOK (set screw to hold the abduction cable - IITCODE : 2490) was glued and blocked.
It has been replaced by a set screw of 2mm (IITCODE : 5807).
thx @spada1978 , @me ;)
