### ISSUE TITLE
icub left_hand's finger (j13-14) gets stuck when I open the hand

### ISSUE THREAD

**Issue by misaki43** [robotology/icub-support#517]
Hello,

In my experiment, I close / open the left hand of the robot. At one trial, when the robot had to open its hand, the middle finger goes in the other direction and got stuck in a totally "closed position".

On Yarpmotorgui we can see that even thought the order position of the joint 13 was something like 7°, it get stuck in bigger value (e.g. in Yarpmotorgui, the position was on the right of the bar even thought the order was on the left).

It was fixed it by turning a screw on the hand, and when I re-launched the robot it worked fine again during some trials. Then, the problem appears again.

Here is the log session, what can I do ?
[log_pc104_yarprobotinterface_965.txt](https://github.com/robotology/icub-support/files/1176631/log_pc104_yarprobotinterface_965.txt)

Thank you for your help!

@serena-ivaldi @dogoepp @olivierrochel-inria 

Oriane

**Comment by dogoepp** [comment]
What we don't understand is why the motor actuating the finger would move in the wrong direction (increasing the error).

The finger's mechanics seems al right, since it can be folded and unfolded manually (when motors are of, by using a screwdriver on the motor's "shaft"). Should I be looking for the an encoder or for something more software-related ?

Besides, we observed that the first joint of the middle finger of both hands is a bit inwards :
![picture of iCub's right hand](https://user-images.githubusercontent.com/13215604/28672333-c3dd1856-72df-11e7-924f-8a8572a21831.jpg)

**Comment by emilio-cartoni** [comment]
@dogoepp maybe the tendon got too much loose (totally unwinded) and now it's winding around its pulley in the wrong direction?
When you turn the motor with the screwdriver and turn clockwise, what does it do?
Is it the same as the motor for another finger? (i.e. they both close or they both open when turned clockwise or does the motor of j13-14 behave differently)

**Comment by julijenv** [comment]
Hi @misaki43  and @dogoepp ,
Could you tell me what is the value of the stretch finger for both joint 13-14, thx in advance.
if not zero, please try to move the magnet in order to get 0 (or close) when stretch.
let me know

**Comment by julijenv** [comment]
Still waiting for feedback on this

**Comment by dogoepp** [comment]
Sorry again for the radio silence. I get to work with iCub only when others use it.

It seems that the problem was "temporary". It suddenly disappeared.
