### ISSUE TITLE
iKinGazeCtrl strange eyes behaviour

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-support#523]
### Description of the failure

After the first month of using the robot seems to behave well except for the eyes, that actually together with the head are the most important parts for our experiments.
 

### Detailed conditions and logs of the failure

As we realized with Julien the first time here in Erzelli by executing the red ball demo, the eyes start shaking very fast during the tracking of the ball.
 
After that we ran other basic tasks and we noticed very similar behaviours. For avoiding that behaviour Ugo suggested us to disable the imu from the IkinGazeCtrl and that was fine, but at this point we should know exactly where the problem is.
 
So I ask you guys if you can come and check one of the next days to try to solve the issue. In the meanwhile if you need more investigations I can also run some test for you or provide you log files or videos, so please let me know if you need my help.

Thank you
---

**Comment by julijenv** [comment]
Hi @ddetommaso ,
it has been unmount the overall eyes part of the head in order to reset the tilt of the eyes that was loose.
After this, it appeared that the robot was behaving not too bad with the red ball demo, it is possible as mentionned by Davide that the IMU just create some disturbances in the posiitonning, but we tried also the iKingazeCtrl to some position it was more than smoooth.
To me the hardware (mechanical and electrical wiring) is OK so I guess that the IMU is responsible for this. I leave this issue open unitil the IMU as been checked by software guy or someone who could check the overall behaviour and try to resolve this software problem.
