### ISSUE TITLE
Board 10.0.1.10 restarted while board 10.0.1.21 did not respond

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#587]
We noticed a weird behaviour of the neck yaw joint, in particular it was moving by itself to a non-zero position (desired reference for position control was zero). Also, the joint was not responding when trying to move it using `yarpmotorgui`. On the logger (attached to this issue), there is an error related to Board 21, that is  not responding. Furthermore, looking at `FirmwareUpdater`, it seems that Board 10 is in IDLE (while all other boards are in RUNNING status). See attached picture. My guess is that the failure was caused by one of these two boards.

![board10_idle](https://user-images.githubusercontent.com/12396934/34267355-ce883d88-e67c-11e7-99b4-a694692aba37.png)

[log_icub-head_neckYaw_broken.txt](https://github.com/robotology/icub-support/files/1579984/log_icub-head_neckYaw_broken.txt)

**Comment by marcoaccame** [comment]
Board 10.0.1.10 is correctly in idle because the skin on the left leg is not enabled. 

The problem is board 10.0.1.21 which seems dead. It is reported dead for 180 seconds before an attempt to read from it:

- @ second 2963 it was working.
``` 18504 2963,827790 <DEBUG>  from BOARD 10.0.1.21 (head-eb21-j2_5), src LOCAL, adr 0, time 37s 420m 410u: (code 0x05000013, par16 0x0000 par64 0x0000000000000000) -> CFG: EOtheMotionController can correctly configure mc4plus-based motion. more info will follow + .```

- @ second 5375 it disappears.
```31419 5375,995928 <DEBUG> EthMonitorPresence: BOARD 10.0.1.21 (head-eb21-j2_5) has been silent for 0.0201006 sec (its timeout is 0.02 sec)```

- @ second 5556 had been silent for 180 seconds.
```32241 5556,001420 <DEBUG> EthMonitorPresence: BOARD 10.0.1.21 (head-eb21-j2_5) has been silent for another 60.0028 sec, for a total of 180.026 sec``` 

- @ second 5587 there was a failed attempt to read from it.
```32430 5587,346282 <ERROR> embObjMotionControl::getLimitsRaw() timed out the wait of reply from BOARD head-eb21-j2_5 IP 10.0.1.21  joint  0```

From the log I cannot understand why it does not respond. Could it be a power supply problem as it happened some weeks ago?
