### ISSUE TITLE
Issue with neck joints acceleration measurement

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#622]
By looking at the `joint accelerations` estimation from the port `yarp read ... /icub/head/stateExt:o`, one can see that the measured joint acceleration on the neck joints suddenly goes to a crazy value (-5493.17747357782 [deg/s^2]) as you can see in the picture:

![screenshot from 2018-04-05 12-26-56](https://user-images.githubusercontent.com/12396934/38361135-abd63ebe-38cc-11e8-9772-e6ebad531345.png)

and this is a plot of the head joints accelerations (from stateExt):

![screenshot from 2018-04-05 12-47-12](https://user-images.githubusercontent.com/12396934/38362004-9f1cfdb8-38cf-11e8-929c-2018618f135c.png)

this is affecting the estimation of the joint torques and external forces that is done by taking into account joints position, velocity and acceleration. This is the result: fake estimated external forces forces are wrongly estimated all over the robot:

![out](https://user-images.githubusercontent.com/12396934/38360973-1f2e23d2-38cc-11e8-96a0-7f6420ee1192.gif)

It is not clear to me if this issue is related to the neck encoders or to the computation of the joint acceleration.

**Comment by traversaro** [comment]
For the time being, I added an option in the `wholebodydynamics` device to disable the use of joint accelerations, see https://github.com/robotology/codyco-modules/pull/262 .

**Comment by randaz81** [comment]
Actually this number seems to be the result of the following operation:
0.03295906 - 0.02746588= 0.00549318 * 1.000.000 = 5493.18

which is incorrectly considering the position of different joints!!! (joint 3 - joint 2)
In the previous message, looking at the very small numbers in the picture, I did the same error done by the machine!!!!

**Comment by randaz81** [comment]
@valegagge @ale-git  please check the acceleration computation in the firmware, there is probably an error in the index of the array.

**Comment by nunoguedelha** [comment]
@randaz81 , if I understood well, you compute the acceleration as follows for a given joint:
```
(pos(t+dt) - pos(t)) / dt^2
```
in that case, this is not correct, since the acceleration is the derivative of the velocity. If we relate to the velocities at t and t+dt, we get:
```
acc(t) = ( vel(t+dt) - vel(t) ) / dt
          = ( pos(t+2*dt) -pos(t+dt) - pos(t+dt) + pos(t) ) / dt^2
          = ( pos(t+2*dt) -2*pos(t+dt) + pos(t) ) / dt^2
```
the result acc(t) would be available at t+2*dt.

If we instead do the symetrical derivative, we get: 
```
acc(t) = (vel(t+dt) - vel(t-dt) ) / (2*dt)
          = ( pos(t+2*dt) -pos(t) - pos(t) + pos(t-2*dt) ) / (2*dt)^2
          = ( pos(t+2*dt) -2*pos(t) + pos(t-2*dt) ) / (2*dt)^2
```
the result acc(t) would be available at t+2*dt, but we get a better approximation than in the first case, assuming that the signal pos(t) is properly filtered in both cases.

**Comment by randaz81** [comment]
we compute the acceleration as the derivative of the velocity.

**Comment by DanielePucci** [comment]
@randaz81 
Thanks for clarifying. For the sake of completeness, may you point the line of code where calculations occur?

**Comment by randaz81** [comment]
After some thinking, I have changed my mind again. I think my first post was the correct one. Here is the longer explanation.

First of all, please observe that the two numbers 0.03295906, 0.02746588 have an exact ratio of 1.2=6/5, meaning that the resolution of the encoder is 0.0054932. This also means that the two numbers are just one encoder tick apart. Thus it is very likely to see them as recurrent magic numbers in the dump of /iCub/head/stateExt:o.

Then we have to consider the fact that velocity and acceleration are computed in the firmware every millisecond, but the dump reports data every 10 milliseconds, so the information about the internal status of estimator is incomplete.

In my first post, I was only inclined to demonstrate that the 5000deg/s2 value was not absurd given those inputs, and my computation was only an approximation to grasp the order of magnitude. I was not computing the derivative using the position. Then I was surprised to get that exact value, hence I suspected the bug mentioned in my second post.

However...

in light of the facts mentioned above, it is still possible that those numbers are correct and identical to the ones computed with the wrong joints **just for coincidence**:
Let's consider the following temporal sequence:
```
TIME        POS                   VEL            ACC
0          0.02746588           0                0
1          0.02746588           0                0
2          0.03295906           5.4932           0
3          0.03295906           0                5493
```
It thus seems that 5493 deg/s^2 is the minimum quantum for an acceleration computed with finite differences (no filtering) given the resolution of that joint.
Moreover, please note that this specific joint is controlled by an mc4plus board equipped with joint and quadrature motor encoders, but with coarser resolution respect to the legs joints, which have access to a high resolution motor encoder (ROIE)
The only thing that I cannot understand is that this specific joint should have an encoder resolution of 360/(2048*100)=0.0017578 instead of 0.0054932 (the value mentioned above). But of course there must be an explanation somewhere...

PS: for comparison, an AEA placed directly on an arm joint has a resolution of 360/4096=0.08789 deg and a leg equipped with roie on the motor has a resolution of 360/(14400*100)=0.00025. In this latter case the minimum rapresentable acceleration (with finite differences) is 250deg/s^2.

PS2: A possibile action point should consider the implementation of a filter to improve the acceleration estimation on the board. The filter could have a configurable fixed windows size = 1 for leg joints and a larger one for joints like the neck. However, this operation will introduce a delay.

**Comment by randaz81** [comment]
> For the sake of completeness, may you point the line of code where calculations occur?

The line of code may change from branch to branch but actually this ultra simple computation is performed in jointSet.c

```
    for (js=0; js<N; ++js)
    {
        j = o->joints_of_set[js];
        o->joint[j].acc_fbk = CTRL_LOOP_FREQUENCY*(o->joint[j].vel_fbk - o->joint[j].vel_fbk_old);
        o->joint[j].vel_fbk_old = o->joint[j].vel_fbk;
    }
```

while this is a mobile window filter employed on CAN boards (not in EMS)

```
//joint velocity estimator
tailJntPos[i]=headJntPos[i]+(winSizeMax-divJntPos[i]); if(tailJntPos[i]>=winSizeMax) tailJntPos[i]=tailJntPos[i]%winSizeMax;			
_speed_old[i] = _speed[i];
jntPosWindow[headJntPos[i]][i]=_position[i];
_speed[i] = ((jntPosWindow[headJntPos[i]][i] - jntPosWindow[tailJntPos[i]][i] ));
_speed[i] <<= _jntVel_est_shift[i];
_speed[i] = (Int32)(_speed[i]) / divJntPos[i];
headJntPos[i]=headJntPos[i]+1; if(headJntPos[i]>=winSizeMax) headJntPos[i]=0;

//joint acceleration estimator
tailJntVel[i]=headJntVel[i]+(winSizeMax-divJntVel[i]); if(tailJntVel[i]>=winSizeMax) tailJntVel[i]=tailJntVel[i]%winSizeMax;			
_accel_old[i] = _accel[i];
jntVelWindow[headJntVel[i]][i]=_speed[i];
_accel[i] = ((jntVelWindow[headJntVel[i]][i] - jntVelWindow[tailJntVel[i]][i] ));
_accel[i] << _jntAcc_est_shift[i];
_accel[i] = (Int32)(_accel[i]) / divJntVel[i];
headJntVel[i]=headJntVel[i]+1; if(headJntVel[i]>=winSizeMax) headJntVel[i]=0;

```

**Comment by randaz81** [comment]
Further discussion on next steps and what to implement in new firmware release requires a f2f meeting.
