### ISSUE TITLE
Issues booting new live image on pc104

### ISSUE THREAD

**Issue by pi-q** [robotology/icub-support#666]
Hello!

We created a new USB drive with live image for the pc104, following the instructions in http://wiki.icub.org/wiki/The_Linux_on_the_pc104.

Once done, we tested it by booting it through another pc: it boots without issue and we could establish network connection; ssh pc104 works.

However, when we plugged the USB drive into the iCub head, we found that we were unable to reach pc104 (either by ping or ssh).

What should be our next step in figuring out what is the problem? 

At the moment we do not have a VGA cable that can connect to the pc104, but we could hack one following instructions in [http://svn.robotology.eu/repos/iCubHardware-pub/trunk/mechanics/public/doc/howTo/Connect_VGA_to_PC104.pdf](http://svn.robotology.eu/repos/iCubHardware-pub/trunk/mechanics/public/doc/howTo/Connect_VGA_to_PC104.pdf). Otherwise we were wondering if we could use a USB hub to connect the USB drive + a monitor (through USB->VGA adaptor that we could buy); is there any reason that this solution would not work?

@InriaBrice @dogoepp @serena-ivaldi

**Comment by julijenv** [comment]
Hi @pi-q , 
i just update the file describe howto make the PC104 to VGA cable you may find some part component to buy to build it. and some pictures

**Comment by pi-q** [comment]
We managed to boot from the USB key on another pc (not on the pc104) to check if there were issues. There is an error message when booting:

Error missing /isolinux/splash.png
Press a key to continue

Would it be possible that the PC104 is not booting because it is stuck on this " missing splashscreen" ?

**Comment by julijenv** [comment]
Hi @pi-q,
I double check, the update is ok?
just scroll down the pdf file it is 3 pages long now

**Comment by pi-q** [comment]
Hi @julijenv,

From here it does not seem so. We followed this link: [https://svn.robotology.eu/repos/iCubHardware-pub/trunk/mechanics/public/doc/howTo/](https://svn.robotology.eu/repos/iCubHardware-pub/trunk/mechanics/public/doc/howTo/) and there we could find 'Connect_VGA_to_PC104.pdf' and 'Connect_VGA_to_PC104.docx', but both of them are only 2 pages long.

Are we following the wrong link?

**Comment by mbrunettini** [comment]
Hi,
the live system writes some info about the network card bus connection the first time it boots on a machine. This implies that if you boot the live on a desktop and then you plug it to a different machine the network may not work (the new network card can be on a different bus.
To fix this you have two options:

1. quick and dirty - open the file `/etc/udev/rules.d/70-presisten-net.rules` and remove any cople of lines like the following: 

`# PCI device 0x8086:0x10f5 (e1000e)

  SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="00:1f:16:0b:47:4d", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"`

2. clean and easy - burn another USB and FIRST install on the PC104

**Comment by pi-q** [comment]
Hi @mbrunettini,

I am sorry, I was entirely not clear in the first message. The FIRST thing we did was **clean and easy** - burn a new USB and FIRST install it on the PC104. At that point, we observed that we could not establish communication with the PC104. 

It is after that, that we tested it by booting it through another pc, and we observed that it boots without issue and we could establish network connection. We confirmed then that we still obtained the same result (no communication) by connecting it on the PC104 a second time.

We could of course burn yet another USB and FIRST install it on the PC104. However we can expect the results to be the same as above.

**Comment by mbrunettini** [comment]
I've read above: 

''Once done, we tested it by booting it through another pc: it boots without issue and we could establish network connection; ssh pc104 works.

However, when we plugged the USB drive into the iCub head, we found that we were unable to reach pc104 (either by ping or ssh).''

Then I thought it was that kind of issue.
You can anyway try to burn another USB, it is a low cost try.
if it fails again, you should connect a VGA cable to the pc104 to check what's going on. we can support you in the debugging.

**Comment by InriaBrice** [comment]
I have severals question about the VGA cable, first, does the motif of the pins matter ?
![droit_vga](https://user-images.githubusercontent.com/26164754/40982819-833c2b5c-68de-11e8-89d4-658d84789613.png)
![envers_vga](https://user-images.githubusercontent.com/26164754/40982868-a671a3ae-68de-11e8-8e28-155976f684b3.png)

Second thing, there is numbers on this image, and on a VGA cable too, which should be like that : 
![image](https://user-images.githubusercontent.com/26164754/40983104-2a8c0e36-68df-11e8-9b6b-3e33e2f0b600.png)
which seems correspond to the manual
![pins](https://user-images.githubusercontent.com/26164754/40983214-694afd62-68df-11e8-8e6c-1503eeb965e0.png)
but if i look on my VGA, i can see numbers written which are like that : 
![img_20180605_165039](https://user-images.githubusercontent.com/26164754/40983951-09e5c1fc-68e1-11e8-86aa-525a4d5a1bce.jpg)
So if i take the same motif, pin 15 will be at the top corner left, instead of 5,
And if i take it like that it means that pin 1 is pin 5.

So i'm pretty confused here.

Best regards,

**Comment by InriaBrice** [comment]
the output should be a female on the documentation ? and then we add a vga to vga ?

**Comment by serena-ivaldi** [comment]
@mbrunettini we burned another flash card and tried it on the pc104 directly, and it still does not boot (or it is unreachable).

BTW @InriaBrice burned the icub live 2017 version from here: http://www.icub.org/download/pc104-images/

**Comment by julijenv** [comment]
Hi @InriaBrice ,
the config doesnt really matter, actually you are right the connector which plugs into the screen is a male, but whatever if it is a male or a female connector , the numbering remains the same.
Just follow the instruction of the pinout numbers and u should be ok.

**Comment by InriaBrice** [comment]
Hi @julijenv , what is the worst scenario if the pin are not correct ? inverted or what ever

**Comment by julijenv** [comment]
usually the worst scenario is when you dont plug the 2x5 pin connector in the correct position, the immediate result is the cable burns.
hope this help.

**Comment by julijenv** [comment]
ANy news?
@pi-q  @InriaBrice

**Comment by pi-q** [comment]
Hi @mbrunettini, @julijenv,

We should be receiving components for the cable tomorrow, so we hope it will be ready in the morning. Would you be available tomorrow, 2pm, that we can call you then if we need extra help?

**Comment by InriaBrice** [comment]
![img_20180608_140447](https://user-images.githubusercontent.com/26164754/41157200-2368124c-6b25-11e8-8b01-c31d90ce0993.jpg)
There is an issue with the GND on pin 10, it seems it's not correct...

**Comment by InriaBrice** [comment]
Can you give us the documentation of the pc104 board to check the connection ?
Best regards

**Comment by julijenv** [comment]
ooooochhhh!!!
hi @InriaBrice , @serena-ivaldi , @pi-q 
here is the cabling scheme pin tp pin in between 10 pin connector to db15.
ksut follow that.
[db15to10pinCon.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/564dabdcd8616f15001b0f59/125516c66e82c728ace21e0d46ec96cb76968cf8dff9b64d8752fed665043761260ea62864c7b96aea142f000b0946fd140b0a11fafc8178a6b668778e5f09bec3714d36976345f3e5db55ea43a82a994e8dbcbd8f4ec8ec3a22e2888c4c36161755.xlsx)

**Comment by julijenv** [comment]
Hi @InriaBrice , sorry, my bad, cable DB15pin connector pin 13 is attcachd to pin 9 of connector 10pin
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/564dabdcd8616f15001b0f59/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f57f7181e570be4778040a594ba412585f10fbfd8a29f5a42062c80d55b98e30063e937f03a6aa8318b500bf22834884b1b48d4cc9e13937aa.JPG)

**Comment by InriaBrice** [comment]
Dorian and I agree on the same thing : this is bullshit. It's making sparks when we just approach (not even connect) the cable to plug it to the screen. And I did the perfect same connection between the pins. Verified again with the multimeter.

**Comment by julijenv** [comment]
Hi @pi-q , @InriaBrice , @dogoepp ,
I triple check again and the last of my pin to pin connection is corerct on 3 of my cables.
here is some pictures that I  took some minutes ago on one of my robot.
![img_20180612_132841](https://user-images.githubusercontent.com/7140395/41288212-dacb8c16-6e45-11e8-94f9-fb2aca4ae326.jpg)
![img_20180612_132856](https://user-images.githubusercontent.com/7140395/41288234-eaeb0d6a-6e45-11e8-82b8-ee1723cfba50.jpg)
My colleagues reminded me that one or more I dont remeber exactley the number got burnt not jsut because of 180 degreee OR that the ground of the TV screen is NOT the same as the one of the robot. Could you check both?!?!

**Comment by InriaBrice** [comment]
I tryed with a new usb key of 16 GB USB 3.0 compatible usb 2.0, instead of 32 GB key, and it seems to work (i mean i can see the machine and ping his IP).

I opened a terminal in the usb key, then su to be as root user. Then 
bash /utils/linux/makeboot.sh /dev/sdc1 (the device for the usb key).

Here it is what i did when running the script :
[makeboot_output.txt](https://github.com/robotology/icub-support/files/2094233/makeboot_output.txt)

**Comment by mbrunettini** [comment]
Just to clarify: please note that `\dev\sdc1` is a **partition** and not a **device**
The corresponding device is `\dev\sdc`
See [this link](https://www.tldp.org/HOWTO/Partition/devices.html)

Then are you able to login to the PC104 now?

**Comment by mbrunettini** [comment]
good news!
I updated the wiki, according to your experience with 32 GB drive, thanks.
Can we close the issue?

**Comment by InriaBrice** [comment]
Yes thanks for the help

**Comment by mbrunettini** [comment]
You're welcome.
Closing issue

**Comment by serena-ivaldi** [comment]
If I may add a comment, we can close the issue because we "solved" the PC104 problem, but the cable problem is still not solved. It would be good to find where is the issue on that as well.. otherwise the problem remains pending / unsolved
