### ISSUE TITLE
Yarprobotinterface does not start with icub_wbd_yoga config file

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#684]
### Description of the failure

I tried to start `iCubGenova02`, but the robot interface exited with the following error:

``` 
[FATAL]Syntax error while loading /usr/local/src/robot/iCubContrib/share/ICUBcontrib/robots/iCubGenova02/./hardware/motorControl/head-eb20-j0_1-mc.xml at line 9 . Expected "device" or "devices". 

```

### Detailed conditions and logs of the failure

Using `yarpmananger`, I run the `yarpRobotInterface --config icub_wbd_yoga.xml` command. The robot interface did not  start. 

Then, I also tried to run the yarpRobotInterface directly on `icub-head`, without the `--config icub_wbd_yoga.xml` option. This time the robot was able to start. I found this quite strange, given the syntax error should be related to a file (head motor control) that I was expecting to be loaded regardless the user specifies or not a configuration file (i.e., `icub_wbd_yoga.xml`).

**NOTE** I also try to run `yarpRobotInterface --config icub_wbd_yoga.xml` directly on `icub-head` but there was the same syntax error reported above.

**Comment by gabrielenava** [comment]
We actually managed to solve the issue. The issue was that the correct `icub_wbd_yoga.xml` file was not loaded, and an old configuration file with the same name was parsed instead. That's why the error was not directly showing an issue with the `icub_wbd_yoga.xml` file. 

Given that we managed to solve the issue, I will close it.

**Comment by nunoguedelha** [comment]
Just a few words about the root cause of this issue. Unlike the **cmake** configuration of `iCubGenova04` configuration files folder, the **cmake** configuration of the `iCubGenova02` folder (`<robots-configuration_ROOT>/iCubGenova02/CMakeLists.txt`) is such that:
- among the `ini` files, only `yarprobotinterface.ini` `firmwareupdater.ini` `general.xml` `iKinGazeCtrl.ini` `icubEyes_ATIS.ini` `icubEyes_DVS.ini` are installed through `$make && make install`
- among the `xml` files, only `icub_all.xml` is installed through `$make && make install`

So any changes to other robot interface configuration files are ignored.

I'm pushing a fix shortly.

CC @traversaro @vibhoraggarwal @S-Dafarra @ahmadgazar

**Comment by nunoguedelha** [comment]
CC @marcoaccame

**Comment by nunoguedelha** [comment]
Fixed by https://github.com/robotology/robots-configuration/pull/72.
