### ISSUE TITLE
iCubErzelli01: burning smell from head

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-support#811]
The robot does not show any particular issue, but a strong burning smell comes from the head.
Further investigations maybe are necessary.

Thank you

**Comment by julijenv** [comment]
The smell is not coming from burnt component but due to the plastic-gummy tape beneath the RS232/USB converter which is directly attached to the Power converter (the hottest component of the head), The smell is not the most pleasant and can be smell just by being very close to the head apart in you case where the smell seems to spread just because the room where the robot is is closed - no ventilation.
There is nothing much that can be done for that, unfortunately.
